#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_cibdo")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void Inserttb_Cuenta(tb_Cuenta instance);
    partial void Updatetb_Cuenta(tb_Cuenta instance);
    partial void Deletetb_Cuenta(tb_Cuenta instance);
    partial void Inserttb_Enfoque_poblacional(tb_Enfoque_poblacional instance);
    partial void Updatetb_Enfoque_poblacional(tb_Enfoque_poblacional instance);
    partial void Deletetb_Enfoque_poblacional(tb_Enfoque_poblacional instance);
    partial void Inserttb_Objetos(tb_Objetos instance);
    partial void Updatetb_Objetos(tb_Objetos instance);
    partial void Deletetb_Objetos(tb_Objetos instance);
    partial void Inserttb_Espacio(tb_Espacio instance);
    partial void Updatetb_Espacio(tb_Espacio instance);
    partial void Deletetb_Espacio(tb_Espacio instance);
    partial void Inserttb_Persona(tb_Persona instance);
    partial void Updatetb_Persona(tb_Persona instance);
    partial void Deletetb_Persona(tb_Persona instance);
    partial void Inserttb_Recordatorios(tb_Recordatorios instance);
    partial void Updatetb_Recordatorios(tb_Recordatorios instance);
    partial void Deletetb_Recordatorios(tb_Recordatorios instance);
    partial void Inserttb_tipo_documento(tb_tipo_documento instance);
    partial void Updatetb_tipo_documento(tb_tipo_documento instance);
    partial void Deletetb_tipo_documento(tb_tipo_documento instance);
    partial void Inserttb_Tipo_espacio(tb_Tipo_espacio instance);
    partial void Updatetb_Tipo_espacio(tb_Tipo_espacio instance);
    partial void Deletetb_Tipo_espacio(tb_Tipo_espacio instance);
    partial void Inserttb_Tipo_recordatorio(tb_Tipo_recordatorio instance);
    partial void Updatetb_Tipo_recordatorio(tb_Tipo_recordatorio instance);
    partial void Deletetb_Tipo_recordatorio(tb_Tipo_recordatorio instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Model.Properties.Settings.Default.db_cibdoConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tb_Cuenta> tb_Cuenta
		{
			get
			{
				return this.GetTable<tb_Cuenta>();
			}
		}
		
		public System.Data.Linq.Table<tb_Enfoque_poblacional> tb_Enfoque_poblacional
		{
			get
			{
				return this.GetTable<tb_Enfoque_poblacional>();
			}
		}
		
		public System.Data.Linq.Table<tb_Objetos> tb_Objetos
		{
			get
			{
				return this.GetTable<tb_Objetos>();
			}
		}
		
		public System.Data.Linq.Table<tb_Espacio> tb_Espacio
		{
			get
			{
				return this.GetTable<tb_Espacio>();
			}
		}
		
		public System.Data.Linq.Table<tb_Persona> tb_Persona
		{
			get
			{
				return this.GetTable<tb_Persona>();
			}
		}
		
		public System.Data.Linq.Table<tb_Recordatorios> tb_Recordatorios
		{
			get
			{
				return this.GetTable<tb_Recordatorios>();
			}
		}
		
		public System.Data.Linq.Table<tb_tipo_documento> tb_tipo_documento
		{
			get
			{
				return this.GetTable<tb_tipo_documento>();
			}
		}
		
		public System.Data.Linq.Table<tb_Tipo_espacio> tb_Tipo_espacio
		{
			get
			{
				return this.GetTable<tb_Tipo_espacio>();
			}
		}
		
		public System.Data.Linq.Table<tb_Tipo_recordatorio> tb_Tipo_recordatorio
		{
			get
			{
				return this.GetTable<tb_Tipo_recordatorio>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.delete_recordatorio")]
		public int delete_recordatorio([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRecordatorio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRecordatorio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_tb_Objeto")]
		public int insert_tb_Objeto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string estado, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, estado, cantidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insert_tb_Recordatorios")]
		public int insert_tb_Recordatorios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> hora, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Persona_idPersona", DbType="Int")] System.Nullable<int> persona_idPersona, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_recordatorio_descripcion", DbType="VarChar(200)")] string tipo_recordatorio_descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, fecha, hora, descripcion, persona_idPersona, tipo_recordatorio_descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_tb_Recordatorios")]
		public ISingleResult<select_tb_RecordatoriosResult> select_tb_Recordatorios()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_tb_RecordatoriosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.update_Recordatorios")]
		public int update_Recordatorios([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idRecordatorio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> hora, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Persona_idPersona", DbType="Int")] System.Nullable<int> persona_idPersona, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Tipo_recordatorio_descripcion", DbType="VarChar(200)")] string tipo_recordatorio_descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idRecordatorio, nombre, fecha, hora, descripcion, persona_idPersona, tipo_recordatorio_descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.select_tipo_recordatorio")]
		public ISingleResult<select_tipo_recordatorioResult> select_tipo_recordatorio()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<select_tipo_recordatorioResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Cuenta")]
	public partial class tb_Cuenta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idCuenta;
		
		private string _usuario;
		
		private string _contraseña;
		
		private EntitySet<tb_Persona> _tb_Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidCuentaChanging(int value);
    partial void OnidCuentaChanged();
    partial void OnusuarioChanging(string value);
    partial void OnusuarioChanged();
    partial void OncontraseñaChanging(string value);
    partial void OncontraseñaChanged();
    #endregion
		
		public tb_Cuenta()
		{
			this._tb_Persona = new EntitySet<tb_Persona>(new Action<tb_Persona>(this.attach_tb_Persona), new Action<tb_Persona>(this.detach_tb_Persona));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idCuenta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idCuenta
		{
			get
			{
				return this._idCuenta;
			}
			set
			{
				if ((this._idCuenta != value))
				{
					this.OnidCuentaChanging(value);
					this.SendPropertyChanging();
					this._idCuenta = value;
					this.SendPropertyChanged("idCuenta");
					this.OnidCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_usuario", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string usuario
		{
			get
			{
				return this._usuario;
			}
			set
			{
				if ((this._usuario != value))
				{
					this.OnusuarioChanging(value);
					this.SendPropertyChanging();
					this._usuario = value;
					this.SendPropertyChanged("usuario");
					this.OnusuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contraseña", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string contraseña
		{
			get
			{
				return this._contraseña;
			}
			set
			{
				if ((this._contraseña != value))
				{
					this.OncontraseñaChanging(value);
					this.SendPropertyChanging();
					this._contraseña = value;
					this.SendPropertyChanged("contraseña");
					this.OncontraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Cuenta_tb_Persona", Storage="_tb_Persona", ThisKey="idCuenta", OtherKey="Cuenta_idCuenta")]
		public EntitySet<tb_Persona> tb_Persona
		{
			get
			{
				return this._tb_Persona;
			}
			set
			{
				this._tb_Persona.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Persona(tb_Persona entity)
		{
			this.SendPropertyChanging();
			entity.tb_Cuenta = this;
		}
		
		private void detach_tb_Persona(tb_Persona entity)
		{
			this.SendPropertyChanging();
			entity.tb_Cuenta = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Enfoque_poblacional")]
	public partial class tb_Enfoque_poblacional : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEnfoque_poblacional;
		
		private string _descripcion;
		
		private EntitySet<tb_Persona> _tb_Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEnfoque_poblacionalChanging(int value);
    partial void OnidEnfoque_poblacionalChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tb_Enfoque_poblacional()
		{
			this._tb_Persona = new EntitySet<tb_Persona>(new Action<tb_Persona>(this.attach_tb_Persona), new Action<tb_Persona>(this.detach_tb_Persona));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEnfoque_poblacional", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEnfoque_poblacional
		{
			get
			{
				return this._idEnfoque_poblacional;
			}
			set
			{
				if ((this._idEnfoque_poblacional != value))
				{
					this.OnidEnfoque_poblacionalChanging(value);
					this.SendPropertyChanging();
					this._idEnfoque_poblacional = value;
					this.SendPropertyChanged("idEnfoque_poblacional");
					this.OnidEnfoque_poblacionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Enfoque_poblacional_tb_Persona", Storage="_tb_Persona", ThisKey="idEnfoque_poblacional", OtherKey="tb_Enfoque_poblacional_idEnfoque_poblacional")]
		public EntitySet<tb_Persona> tb_Persona
		{
			get
			{
				return this._tb_Persona;
			}
			set
			{
				this._tb_Persona.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Persona(tb_Persona entity)
		{
			this.SendPropertyChanging();
			entity.tb_Enfoque_poblacional = this;
		}
		
		private void detach_tb_Persona(tb_Persona entity)
		{
			this.SendPropertyChanging();
			entity.tb_Enfoque_poblacional = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Objetos")]
	public partial class tb_Objetos : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idObjetos;
		
		private string _nombre;
		
		private string _estado;
		
		private int _cantidad;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidObjetosChanging(int value);
    partial void OnidObjetosChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnestadoChanging(string value);
    partial void OnestadoChanged();
    partial void OncantidadChanging(int value);
    partial void OncantidadChanged();
    #endregion
		
		public tb_Objetos()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idObjetos", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idObjetos
		{
			get
			{
				return this._idObjetos;
			}
			set
			{
				if ((this._idObjetos != value))
				{
					this.OnidObjetosChanging(value);
					this.SendPropertyChanging();
					this._idObjetos = value;
					this.SendPropertyChanged("idObjetos");
					this.OnidObjetosChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado
		{
			get
			{
				return this._estado;
			}
			set
			{
				if ((this._estado != value))
				{
					this.OnestadoChanging(value);
					this.SendPropertyChanging();
					this._estado = value;
					this.SendPropertyChanged("estado");
					this.OnestadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cantidad", DbType="Int NOT NULL")]
		public int cantidad
		{
			get
			{
				return this._cantidad;
			}
			set
			{
				if ((this._cantidad != value))
				{
					this.OncantidadChanging(value);
					this.SendPropertyChanging();
					this._cantidad = value;
					this.SendPropertyChanged("cantidad");
					this.OncantidadChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Espacio")]
	public partial class tb_Espacio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idEspacio;
		
		private string _nombre;
		
		private int _costo;
		
		private string _estado_espacio;
		
		private int _Tipo_espacio_idTipo_espacio1;
		
		private EntityRef<tb_Tipo_espacio> _tb_Tipo_espacio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidEspacioChanging(int value);
    partial void OnidEspacioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OncostoChanging(int value);
    partial void OncostoChanged();
    partial void Onestado_espacioChanging(string value);
    partial void Onestado_espacioChanged();
    partial void OnTipo_espacio_idTipo_espacio1Changing(int value);
    partial void OnTipo_espacio_idTipo_espacio1Changed();
    #endregion
		
		public tb_Espacio()
		{
			this._tb_Tipo_espacio = default(EntityRef<tb_Tipo_espacio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEspacio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idEspacio
		{
			get
			{
				return this._idEspacio;
			}
			set
			{
				if ((this._idEspacio != value))
				{
					this.OnidEspacioChanging(value);
					this.SendPropertyChanging();
					this._idEspacio = value;
					this.SendPropertyChanged("idEspacio");
					this.OnidEspacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_costo", DbType="Int NOT NULL")]
		public int costo
		{
			get
			{
				return this._costo;
			}
			set
			{
				if ((this._costo != value))
				{
					this.OncostoChanging(value);
					this.SendPropertyChanging();
					this._costo = value;
					this.SendPropertyChanged("costo");
					this.OncostoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estado_espacio", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estado_espacio
		{
			get
			{
				return this._estado_espacio;
			}
			set
			{
				if ((this._estado_espacio != value))
				{
					this.Onestado_espacioChanging(value);
					this.SendPropertyChanging();
					this._estado_espacio = value;
					this.SendPropertyChanged("estado_espacio");
					this.Onestado_espacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_espacio_idTipo_espacio1", DbType="Int NOT NULL")]
		public int Tipo_espacio_idTipo_espacio1
		{
			get
			{
				return this._Tipo_espacio_idTipo_espacio1;
			}
			set
			{
				if ((this._Tipo_espacio_idTipo_espacio1 != value))
				{
					if (this._tb_Tipo_espacio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipo_espacio_idTipo_espacio1Changing(value);
					this.SendPropertyChanging();
					this._Tipo_espacio_idTipo_espacio1 = value;
					this.SendPropertyChanged("Tipo_espacio_idTipo_espacio1");
					this.OnTipo_espacio_idTipo_espacio1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Tipo_espacio_tb_Espacio", Storage="_tb_Tipo_espacio", ThisKey="Tipo_espacio_idTipo_espacio1", OtherKey="idTipo_espacio", IsForeignKey=true)]
		public tb_Tipo_espacio tb_Tipo_espacio
		{
			get
			{
				return this._tb_Tipo_espacio.Entity;
			}
			set
			{
				tb_Tipo_espacio previousValue = this._tb_Tipo_espacio.Entity;
				if (((previousValue != value) 
							|| (this._tb_Tipo_espacio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Tipo_espacio.Entity = null;
						previousValue.tb_Espacio.Remove(this);
					}
					this._tb_Tipo_espacio.Entity = value;
					if ((value != null))
					{
						value.tb_Espacio.Add(this);
						this._Tipo_espacio_idTipo_espacio1 = value.idTipo_espacio;
					}
					else
					{
						this._Tipo_espacio_idTipo_espacio1 = default(int);
					}
					this.SendPropertyChanged("tb_Tipo_espacio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Persona")]
	public partial class tb_Persona : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idPersona;
		
		private string _nombre;
		
		private string _apellido;
		
		private int _nro_documento;
		
		private System.DateTime _fecha_nacimiento;
		
		private string _eps;
		
		private string _estrato;
		
		private string _direccion;
		
		private int _celular;
		
		private string _sexo;
		
		private string _tipo_persona;
		
		private string _ciudad;
		
		private int _Cuenta_idCuenta;
		
		private int _tb_tipo_documento_id_tipo_documento;
		
		private int _tb_Enfoque_poblacional_idEnfoque_poblacional;
		
		private EntitySet<tb_Recordatorios> _tb_Recordatorios;
		
		private EntityRef<tb_Cuenta> _tb_Cuenta;
		
		private EntityRef<tb_Enfoque_poblacional> _tb_Enfoque_poblacional;
		
		private EntityRef<tb_tipo_documento> _tb_tipo_documento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidPersonaChanging(int value);
    partial void OnidPersonaChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnapellidoChanging(string value);
    partial void OnapellidoChanged();
    partial void Onnro_documentoChanging(int value);
    partial void Onnro_documentoChanged();
    partial void Onfecha_nacimientoChanging(System.DateTime value);
    partial void Onfecha_nacimientoChanged();
    partial void OnepsChanging(string value);
    partial void OnepsChanged();
    partial void OnestratoChanging(string value);
    partial void OnestratoChanged();
    partial void OndireccionChanging(string value);
    partial void OndireccionChanged();
    partial void OncelularChanging(int value);
    partial void OncelularChanged();
    partial void OnsexoChanging(string value);
    partial void OnsexoChanged();
    partial void Ontipo_personaChanging(string value);
    partial void Ontipo_personaChanged();
    partial void OnciudadChanging(string value);
    partial void OnciudadChanged();
    partial void OnCuenta_idCuentaChanging(int value);
    partial void OnCuenta_idCuentaChanged();
    partial void Ontb_tipo_documento_id_tipo_documentoChanging(int value);
    partial void Ontb_tipo_documento_id_tipo_documentoChanged();
    partial void Ontb_Enfoque_poblacional_idEnfoque_poblacionalChanging(int value);
    partial void Ontb_Enfoque_poblacional_idEnfoque_poblacionalChanged();
    #endregion
		
		public tb_Persona()
		{
			this._tb_Recordatorios = new EntitySet<tb_Recordatorios>(new Action<tb_Recordatorios>(this.attach_tb_Recordatorios), new Action<tb_Recordatorios>(this.detach_tb_Recordatorios));
			this._tb_Cuenta = default(EntityRef<tb_Cuenta>);
			this._tb_Enfoque_poblacional = default(EntityRef<tb_Enfoque_poblacional>);
			this._tb_tipo_documento = default(EntityRef<tb_tipo_documento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idPersona", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int idPersona
		{
			get
			{
				return this._idPersona;
			}
			set
			{
				if ((this._idPersona != value))
				{
					this.OnidPersonaChanging(value);
					this.SendPropertyChanging();
					this._idPersona = value;
					this.SendPropertyChanged("idPersona");
					this.OnidPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apellido", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string apellido
		{
			get
			{
				return this._apellido;
			}
			set
			{
				if ((this._apellido != value))
				{
					this.OnapellidoChanging(value);
					this.SendPropertyChanging();
					this._apellido = value;
					this.SendPropertyChanged("apellido");
					this.OnapellidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nro_documento", DbType="Int NOT NULL")]
		public int nro_documento
		{
			get
			{
				return this._nro_documento;
			}
			set
			{
				if ((this._nro_documento != value))
				{
					this.Onnro_documentoChanging(value);
					this.SendPropertyChanging();
					this._nro_documento = value;
					this.SendPropertyChanged("nro_documento");
					this.Onnro_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_nacimiento", DbType="Date NOT NULL")]
		public System.DateTime fecha_nacimiento
		{
			get
			{
				return this._fecha_nacimiento;
			}
			set
			{
				if ((this._fecha_nacimiento != value))
				{
					this.Onfecha_nacimientoChanging(value);
					this.SendPropertyChanging();
					this._fecha_nacimiento = value;
					this.SendPropertyChanged("fecha_nacimiento");
					this.Onfecha_nacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_eps", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string eps
		{
			get
			{
				return this._eps;
			}
			set
			{
				if ((this._eps != value))
				{
					this.OnepsChanging(value);
					this.SendPropertyChanging();
					this._eps = value;
					this.SendPropertyChanged("eps");
					this.OnepsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_estrato", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string estrato
		{
			get
			{
				return this._estrato;
			}
			set
			{
				if ((this._estrato != value))
				{
					this.OnestratoChanging(value);
					this.SendPropertyChanging();
					this._estrato = value;
					this.SendPropertyChanged("estrato");
					this.OnestratoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string direccion
		{
			get
			{
				return this._direccion;
			}
			set
			{
				if ((this._direccion != value))
				{
					this.OndireccionChanging(value);
					this.SendPropertyChanging();
					this._direccion = value;
					this.SendPropertyChanged("direccion");
					this.OndireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_celular", DbType="Int NOT NULL")]
		public int celular
		{
			get
			{
				return this._celular;
			}
			set
			{
				if ((this._celular != value))
				{
					this.OncelularChanging(value);
					this.SendPropertyChanging();
					this._celular = value;
					this.SendPropertyChanged("celular");
					this.OncelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sexo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sexo
		{
			get
			{
				return this._sexo;
			}
			set
			{
				if ((this._sexo != value))
				{
					this.OnsexoChanging(value);
					this.SendPropertyChanging();
					this._sexo = value;
					this.SendPropertyChanged("sexo");
					this.OnsexoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_persona", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tipo_persona
		{
			get
			{
				return this._tipo_persona;
			}
			set
			{
				if ((this._tipo_persona != value))
				{
					this.Ontipo_personaChanging(value);
					this.SendPropertyChanging();
					this._tipo_persona = value;
					this.SendPropertyChanged("tipo_persona");
					this.Ontipo_personaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ciudad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ciudad
		{
			get
			{
				return this._ciudad;
			}
			set
			{
				if ((this._ciudad != value))
				{
					this.OnciudadChanging(value);
					this.SendPropertyChanging();
					this._ciudad = value;
					this.SendPropertyChanged("ciudad");
					this.OnciudadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cuenta_idCuenta", DbType="Int NOT NULL")]
		public int Cuenta_idCuenta
		{
			get
			{
				return this._Cuenta_idCuenta;
			}
			set
			{
				if ((this._Cuenta_idCuenta != value))
				{
					if (this._tb_Cuenta.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCuenta_idCuentaChanging(value);
					this.SendPropertyChanging();
					this._Cuenta_idCuenta = value;
					this.SendPropertyChanged("Cuenta_idCuenta");
					this.OnCuenta_idCuentaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_tipo_documento_id_tipo_documento", DbType="Int NOT NULL")]
		public int tb_tipo_documento_id_tipo_documento
		{
			get
			{
				return this._tb_tipo_documento_id_tipo_documento;
			}
			set
			{
				if ((this._tb_tipo_documento_id_tipo_documento != value))
				{
					if (this._tb_tipo_documento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontb_tipo_documento_id_tipo_documentoChanging(value);
					this.SendPropertyChanging();
					this._tb_tipo_documento_id_tipo_documento = value;
					this.SendPropertyChanged("tb_tipo_documento_id_tipo_documento");
					this.Ontb_tipo_documento_id_tipo_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tb_Enfoque_poblacional_idEnfoque_poblacional", DbType="Int NOT NULL")]
		public int tb_Enfoque_poblacional_idEnfoque_poblacional
		{
			get
			{
				return this._tb_Enfoque_poblacional_idEnfoque_poblacional;
			}
			set
			{
				if ((this._tb_Enfoque_poblacional_idEnfoque_poblacional != value))
				{
					if (this._tb_Enfoque_poblacional.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontb_Enfoque_poblacional_idEnfoque_poblacionalChanging(value);
					this.SendPropertyChanging();
					this._tb_Enfoque_poblacional_idEnfoque_poblacional = value;
					this.SendPropertyChanged("tb_Enfoque_poblacional_idEnfoque_poblacional");
					this.Ontb_Enfoque_poblacional_idEnfoque_poblacionalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Persona_tb_Recordatorios", Storage="_tb_Recordatorios", ThisKey="idPersona", OtherKey="Persona_idPersona")]
		public EntitySet<tb_Recordatorios> tb_Recordatorios
		{
			get
			{
				return this._tb_Recordatorios;
			}
			set
			{
				this._tb_Recordatorios.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Cuenta_tb_Persona", Storage="_tb_Cuenta", ThisKey="Cuenta_idCuenta", OtherKey="idCuenta", IsForeignKey=true)]
		public tb_Cuenta tb_Cuenta
		{
			get
			{
				return this._tb_Cuenta.Entity;
			}
			set
			{
				tb_Cuenta previousValue = this._tb_Cuenta.Entity;
				if (((previousValue != value) 
							|| (this._tb_Cuenta.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Cuenta.Entity = null;
						previousValue.tb_Persona.Remove(this);
					}
					this._tb_Cuenta.Entity = value;
					if ((value != null))
					{
						value.tb_Persona.Add(this);
						this._Cuenta_idCuenta = value.idCuenta;
					}
					else
					{
						this._Cuenta_idCuenta = default(int);
					}
					this.SendPropertyChanged("tb_Cuenta");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Enfoque_poblacional_tb_Persona", Storage="_tb_Enfoque_poblacional", ThisKey="tb_Enfoque_poblacional_idEnfoque_poblacional", OtherKey="idEnfoque_poblacional", IsForeignKey=true)]
		public tb_Enfoque_poblacional tb_Enfoque_poblacional
		{
			get
			{
				return this._tb_Enfoque_poblacional.Entity;
			}
			set
			{
				tb_Enfoque_poblacional previousValue = this._tb_Enfoque_poblacional.Entity;
				if (((previousValue != value) 
							|| (this._tb_Enfoque_poblacional.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Enfoque_poblacional.Entity = null;
						previousValue.tb_Persona.Remove(this);
					}
					this._tb_Enfoque_poblacional.Entity = value;
					if ((value != null))
					{
						value.tb_Persona.Add(this);
						this._tb_Enfoque_poblacional_idEnfoque_poblacional = value.idEnfoque_poblacional;
					}
					else
					{
						this._tb_Enfoque_poblacional_idEnfoque_poblacional = default(int);
					}
					this.SendPropertyChanged("tb_Enfoque_poblacional");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_tipo_documento_tb_Persona", Storage="_tb_tipo_documento", ThisKey="tb_tipo_documento_id_tipo_documento", OtherKey="id_tipo_documento", IsForeignKey=true)]
		public tb_tipo_documento tb_tipo_documento
		{
			get
			{
				return this._tb_tipo_documento.Entity;
			}
			set
			{
				tb_tipo_documento previousValue = this._tb_tipo_documento.Entity;
				if (((previousValue != value) 
							|| (this._tb_tipo_documento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_tipo_documento.Entity = null;
						previousValue.tb_Persona.Remove(this);
					}
					this._tb_tipo_documento.Entity = value;
					if ((value != null))
					{
						value.tb_Persona.Add(this);
						this._tb_tipo_documento_id_tipo_documento = value.id_tipo_documento;
					}
					else
					{
						this._tb_tipo_documento_id_tipo_documento = default(int);
					}
					this.SendPropertyChanged("tb_tipo_documento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Recordatorios(tb_Recordatorios entity)
		{
			this.SendPropertyChanging();
			entity.tb_Persona = this;
		}
		
		private void detach_tb_Recordatorios(tb_Recordatorios entity)
		{
			this.SendPropertyChanging();
			entity.tb_Persona = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Recordatorios")]
	public partial class tb_Recordatorios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idRecordatorio;
		
		private string _nombre;
		
		private System.DateTime _fecha;
		
		private System.TimeSpan _hora;
		
		private string _descripcion;
		
		private int _Persona_idPersona;
		
		private string _Tipo_recordatorio_descripcion;
		
		private EntityRef<tb_Persona> _tb_Persona;
		
		private EntityRef<tb_Tipo_recordatorio> _tb_Tipo_recordatorio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidRecordatorioChanging(int value);
    partial void OnidRecordatorioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnfechaChanging(System.DateTime value);
    partial void OnfechaChanged();
    partial void OnhoraChanging(System.TimeSpan value);
    partial void OnhoraChanged();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    partial void OnPersona_idPersonaChanging(int value);
    partial void OnPersona_idPersonaChanged();
    partial void OnTipo_recordatorio_descripcionChanging(string value);
    partial void OnTipo_recordatorio_descripcionChanged();
    #endregion
		
		public tb_Recordatorios()
		{
			this._tb_Persona = default(EntityRef<tb_Persona>);
			this._tb_Tipo_recordatorio = default(EntityRef<tb_Tipo_recordatorio>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecordatorio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idRecordatorio
		{
			get
			{
				return this._idRecordatorio;
			}
			set
			{
				if ((this._idRecordatorio != value))
				{
					this.OnidRecordatorioChanging(value);
					this.SendPropertyChanging();
					this._idRecordatorio = value;
					this.SendPropertyChanged("idRecordatorio");
					this.OnidRecordatorioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this.OnfechaChanging(value);
					this.SendPropertyChanging();
					this._fecha = value;
					this.SendPropertyChanged("fecha");
					this.OnfechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time NOT NULL")]
		public System.TimeSpan hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this.OnhoraChanging(value);
					this.SendPropertyChanging();
					this._hora = value;
					this.SendPropertyChanged("hora");
					this.OnhoraChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_idPersona", DbType="Int NOT NULL")]
		public int Persona_idPersona
		{
			get
			{
				return this._Persona_idPersona;
			}
			set
			{
				if ((this._Persona_idPersona != value))
				{
					if (this._tb_Persona.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPersona_idPersonaChanging(value);
					this.SendPropertyChanging();
					this._Persona_idPersona = value;
					this.SendPropertyChanged("Persona_idPersona");
					this.OnPersona_idPersonaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_recordatorio_descripcion", DbType="VarChar(200)")]
		public string Tipo_recordatorio_descripcion
		{
			get
			{
				return this._Tipo_recordatorio_descripcion;
			}
			set
			{
				if ((this._Tipo_recordatorio_descripcion != value))
				{
					if (this._tb_Tipo_recordatorio.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTipo_recordatorio_descripcionChanging(value);
					this.SendPropertyChanging();
					this._Tipo_recordatorio_descripcion = value;
					this.SendPropertyChanged("Tipo_recordatorio_descripcion");
					this.OnTipo_recordatorio_descripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Persona_tb_Recordatorios", Storage="_tb_Persona", ThisKey="Persona_idPersona", OtherKey="idPersona", IsForeignKey=true)]
		public tb_Persona tb_Persona
		{
			get
			{
				return this._tb_Persona.Entity;
			}
			set
			{
				tb_Persona previousValue = this._tb_Persona.Entity;
				if (((previousValue != value) 
							|| (this._tb_Persona.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Persona.Entity = null;
						previousValue.tb_Recordatorios.Remove(this);
					}
					this._tb_Persona.Entity = value;
					if ((value != null))
					{
						value.tb_Recordatorios.Add(this);
						this._Persona_idPersona = value.idPersona;
					}
					else
					{
						this._Persona_idPersona = default(int);
					}
					this.SendPropertyChanged("tb_Persona");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Tipo_recordatorio_tb_Recordatorios", Storage="_tb_Tipo_recordatorio", ThisKey="Tipo_recordatorio_descripcion", OtherKey="descripcion", IsForeignKey=true)]
		public tb_Tipo_recordatorio tb_Tipo_recordatorio
		{
			get
			{
				return this._tb_Tipo_recordatorio.Entity;
			}
			set
			{
				tb_Tipo_recordatorio previousValue = this._tb_Tipo_recordatorio.Entity;
				if (((previousValue != value) 
							|| (this._tb_Tipo_recordatorio.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tb_Tipo_recordatorio.Entity = null;
						previousValue.tb_Recordatorios.Remove(this);
					}
					this._tb_Tipo_recordatorio.Entity = value;
					if ((value != null))
					{
						value.tb_Recordatorios.Add(this);
						this._Tipo_recordatorio_descripcion = value.descripcion;
					}
					else
					{
						this._Tipo_recordatorio_descripcion = default(string);
					}
					this.SendPropertyChanged("tb_Tipo_recordatorio");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_tipo_documento")]
	public partial class tb_tipo_documento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_tipo_documento;
		
		private string _nombre;
		
		private string _abreviado;
		
		private EntitySet<tb_Persona> _tb_Persona;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_tipo_documentoChanging(int value);
    partial void Onid_tipo_documentoChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    partial void OnabreviadoChanging(string value);
    partial void OnabreviadoChanged();
    #endregion
		
		public tb_tipo_documento()
		{
			this._tb_Persona = new EntitySet<tb_Persona>(new Action<tb_Persona>(this.attach_tb_Persona), new Action<tb_Persona>(this.detach_tb_Persona));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_tipo_documento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_tipo_documento
		{
			get
			{
				return this._id_tipo_documento;
			}
			set
			{
				if ((this._id_tipo_documento != value))
				{
					this.Onid_tipo_documentoChanging(value);
					this.SendPropertyChanging();
					this._id_tipo_documento = value;
					this.SendPropertyChanged("id_tipo_documento");
					this.Onid_tipo_documentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_abreviado", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string abreviado
		{
			get
			{
				return this._abreviado;
			}
			set
			{
				if ((this._abreviado != value))
				{
					this.OnabreviadoChanging(value);
					this.SendPropertyChanging();
					this._abreviado = value;
					this.SendPropertyChanged("abreviado");
					this.OnabreviadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_tipo_documento_tb_Persona", Storage="_tb_Persona", ThisKey="id_tipo_documento", OtherKey="tb_tipo_documento_id_tipo_documento")]
		public EntitySet<tb_Persona> tb_Persona
		{
			get
			{
				return this._tb_Persona;
			}
			set
			{
				this._tb_Persona.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Persona(tb_Persona entity)
		{
			this.SendPropertyChanging();
			entity.tb_tipo_documento = this;
		}
		
		private void detach_tb_Persona(tb_Persona entity)
		{
			this.SendPropertyChanging();
			entity.tb_tipo_documento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Tipo_espacio")]
	public partial class tb_Tipo_espacio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTipo_espacio;
		
		private string _nombre;
		
		private EntitySet<tb_Espacio> _tb_Espacio;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTipo_espacioChanging(int value);
    partial void OnidTipo_espacioChanged();
    partial void OnnombreChanging(string value);
    partial void OnnombreChanged();
    #endregion
		
		public tb_Tipo_espacio()
		{
			this._tb_Espacio = new EntitySet<tb_Espacio>(new Action<tb_Espacio>(this.attach_tb_Espacio), new Action<tb_Espacio>(this.detach_tb_Espacio));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTipo_espacio", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTipo_espacio
		{
			get
			{
				return this._idTipo_espacio;
			}
			set
			{
				if ((this._idTipo_espacio != value))
				{
					this.OnidTipo_espacioChanging(value);
					this.SendPropertyChanging();
					this._idTipo_espacio = value;
					this.SendPropertyChanged("idTipo_espacio");
					this.OnidTipo_espacioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this.OnnombreChanging(value);
					this.SendPropertyChanging();
					this._nombre = value;
					this.SendPropertyChanged("nombre");
					this.OnnombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Tipo_espacio_tb_Espacio", Storage="_tb_Espacio", ThisKey="idTipo_espacio", OtherKey="Tipo_espacio_idTipo_espacio1")]
		public EntitySet<tb_Espacio> tb_Espacio
		{
			get
			{
				return this._tb_Espacio;
			}
			set
			{
				this._tb_Espacio.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Espacio(tb_Espacio entity)
		{
			this.SendPropertyChanging();
			entity.tb_Tipo_espacio = this;
		}
		
		private void detach_tb_Espacio(tb_Espacio entity)
		{
			this.SendPropertyChanging();
			entity.tb_Tipo_espacio = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Tipo_recordatorio")]
	public partial class tb_Tipo_recordatorio : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _descripcion;
		
		private EntitySet<tb_Recordatorios> _tb_Recordatorios;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OndescripcionChanging(string value);
    partial void OndescripcionChanged();
    #endregion
		
		public tb_Tipo_recordatorio()
		{
			this._tb_Recordatorios = new EntitySet<tb_Recordatorios>(new Action<tb_Recordatorios>(this.attach_tb_Recordatorios), new Action<tb_Recordatorios>(this.detach_tb_Recordatorios));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this.OndescripcionChanging(value);
					this.SendPropertyChanging();
					this._descripcion = value;
					this.SendPropertyChanged("descripcion");
					this.OndescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tb_Tipo_recordatorio_tb_Recordatorios", Storage="_tb_Recordatorios", ThisKey="descripcion", OtherKey="Tipo_recordatorio_descripcion")]
		public EntitySet<tb_Recordatorios> tb_Recordatorios
		{
			get
			{
				return this._tb_Recordatorios;
			}
			set
			{
				this._tb_Recordatorios.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tb_Recordatorios(tb_Recordatorios entity)
		{
			this.SendPropertyChanging();
			entity.tb_Tipo_recordatorio = this;
		}
		
		private void detach_tb_Recordatorios(tb_Recordatorios entity)
		{
			this.SendPropertyChanging();
			entity.tb_Tipo_recordatorio = null;
		}
	}
	
	public partial class select_tb_RecordatoriosResult
	{
		
		private int _idRecordatorio;
		
		private string _nombre;
		
		private System.DateTime _fecha;
		
		private System.TimeSpan _hora;
		
		private string _descripcion;
		
		private int _Persona_idPersona;
		
		private string _Tipo_recordatorio_descripcion;
		
		public select_tb_RecordatoriosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idRecordatorio", DbType="Int NOT NULL")]
		public int idRecordatorio
		{
			get
			{
				return this._idRecordatorio;
			}
			set
			{
				if ((this._idRecordatorio != value))
				{
					this._idRecordatorio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string nombre
		{
			get
			{
				return this._nombre;
			}
			set
			{
				if ((this._nombre != value))
				{
					this._nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha", DbType="Date NOT NULL")]
		public System.DateTime fecha
		{
			get
			{
				return this._fecha;
			}
			set
			{
				if ((this._fecha != value))
				{
					this._fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hora", DbType="Time NOT NULL")]
		public System.TimeSpan hora
		{
			get
			{
				return this._hora;
			}
			set
			{
				if ((this._hora != value))
				{
					this._hora = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Persona_idPersona", DbType="Int NOT NULL")]
		public int Persona_idPersona
		{
			get
			{
				return this._Persona_idPersona;
			}
			set
			{
				if ((this._Persona_idPersona != value))
				{
					this._Persona_idPersona = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tipo_recordatorio_descripcion", DbType="VarChar(200)")]
		public string Tipo_recordatorio_descripcion
		{
			get
			{
				return this._Tipo_recordatorio_descripcion;
			}
			set
			{
				if ((this._Tipo_recordatorio_descripcion != value))
				{
					this._Tipo_recordatorio_descripcion = value;
				}
			}
		}
	}
	
	public partial class select_tipo_recordatorioResult
	{
		
		private string _descripcion;
		
		public select_tipo_recordatorioResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_descripcion", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string descripcion
		{
			get
			{
				return this._descripcion;
			}
			set
			{
				if ((this._descripcion != value))
				{
					this._descripcion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
